import {test} from 'node:test';
import assert from 'node:assert/strict';
import {act,advance,view,replaySchedule,kind,VOTE_MS} from '../lib/game.ts';
function create(n=3){const r={code:'ABCDEF',host:'0',players:Array.from({length:n},(_,i)=>({id:String(i),secret:String(i),name:'player'+i,ready:true})),phase:'lobby',game:'',round:0,duration:60,deadline:0,entries:[]};act(r,'0',{action:'start',duration:60},1);return r}
function finish(r){while(r.phase==='play'){const round=r.round;for(const p of r.players)act(r,p.secret,{action:'submit',game:r.game,round,...(round===0?{text:r.prompts[p.id].deck[0]}:kind(round)==='text'?{text:'guess'+p.id}:{imageKey:'drawing'+round+p.id})},round+2)}return replaySchedule(r).endsAt}
function vote(r,id,success,now){act(r,id,{action:'vote',game:r.game,album:r.replayAlbum,success},now)}
test('3 through 12 players draw their own choice and every chain ends with a guess',()=>{for(let n=3;n<=12;n++){const r=create(n);for(const p of r.players)act(r,p.secret,{action:'submit',game:r.game,round:0,text:r.prompts[p.id].deck[0]},2);for(const p of r.players){const v=view(r,p.secret,1);assert.equal(v.previous.author,p.id);assert.equal(v.previousPlayer.id,p.id)}const rounds=r.entries.length;assert.equal(kind(rounds-1),'text');finish(r);const albums=view(r,'0',0).albums;for(let i=0;i<n;i++){assert.equal(albums[i].entries[0].author,String(i));assert.equal(albums[i].entries[1].author,String(i));for(let j=2;j<rounds;j++)assert.equal(albums[i].entries[j].author,String((i+j-1)%n));assert.equal(albums[i].entries.at(-1).kind,'text')}assert.equal(replaySchedule(r).steps.length,rounds)}});
test('each replay pauses for one immutable vote per player, then publishes the majority and advances',()=>{const r=create(),end=finish(r);assert.throws(()=>vote(r,'0',true,end-1));assert.throws(()=>act(r,'0',{action:'return',game:r.game},end));vote(r,'0',true,end);vote(r,'0',false,end);assert.equal(r.votes[0]['0'],true);assert.equal(view(r,'1',0).votes,undefined);assert.equal(r.replayAlbum,0);vote(r,'1',false,end);vote(r,'2',true,end);assert.deepEqual(r.verdicts[0],{album:0,yes:2,no:1,abstained:0,success:true});assert.equal(r.replayAlbum,1);assert.equal(r.replayStartsAt,end+5000);assert.throws(()=>act(r,'0',{action:'vote',game:r.game,album:0,success:true},end));while(!r.replayFinished){const t=replaySchedule(r).endsAt;for(const id of ['0','1','2'])vote(r,id,true,t)}assert.equal(r.verdicts.length,3);assert.equal(r.replayFinished,true);act(r,'0',{action:'return',game:r.game},replaySchedule(r).endsAt);assert.equal(view(r,'0',0).phase,'lobby')});
test('timeout abstentions and ties never count as success, and departed players stop blocking votes',()=>{const r=create(),end=finish(r);vote(r,'0',true,end);vote(r,'1',false,end);assert.equal(advance(r,end+VOTE_MS-1),false);advance(r,end+VOTE_MS);assert.deepEqual(r.verdicts[0],{album:0,yes:1,no:1,abstained:1,success:false});const next=replaySchedule(r).endsAt;act(r,'2',{action:'leave'},next);vote(r,'0',false,next);vote(r,'1',false,next);assert.equal(r.verdicts[1].success,false);assert.equal(r.verdicts[1].abstained,0);assert.throws(()=>act(r,'0',{action:'vote',game:'stale',album:2,success:true},next));});
