"use client";
import { forwardRef, useEffect, useImperativeHandle, useRef, useState } from 'react';
import { Pencil, Eraser, Undo2, Redo2, Trash2, Check } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
type Point={x:number;y:number};
type Stroke={color:string;width:number;points:Point[];clear?:boolean};
export type CanvasHandle={image:()=>string;hasDrawing:()=>boolean};
const colors=['#202943','#2548f4','#8b54db','#f05a51','#f59e28','#f9d648','#92c94b','#39aa8c','#68c9ea','#e88cac'];
export const DrawingCanvas=forwardRef<CanvasHandle,{draftKey:string;compact?:boolean;disabled?:boolean}>(function DrawingCanvas({draftKey,compact,disabled},ref){
  const canvas=useRef<HTMLCanvasElement>(null),active=useRef<Stroke|null>(null),pointer=useRef<number|null>(null);
  const [strokes,setStrokes]=useState<Stroke[]>([]),[redo,setRedo]=useState<Stroke[]>([]),[color,setColor]=useState(colors[0]),[width,setWidth]=useState(6),[eraser,setEraser]=useState(false),[loaded,setLoaded]=useState(false);
  function segment(ctx:CanvasRenderingContext2D,s:Stroke){if(s.clear){ctx.fillStyle='#fff';ctx.fillRect(0,0,960,600);return}ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=s.width;ctx.strokeStyle=s.color;ctx.fillStyle=s.color;ctx.beginPath();s.points.forEach((p,i)=>{if(!i)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y)});ctx.stroke();if(s.points.length===1){ctx.beginPath();ctx.arc(s.points[0].x,s.points[0].y,s.width/2,0,Math.PI*2);ctx.fill()}}
  function paint(){const ctx=canvas.current?.getContext('2d');if(!ctx)return;ctx.fillStyle='#fff';ctx.fillRect(0,0,960,600);strokes.forEach(s=>segment(ctx,s));if(active.current)segment(ctx,active.current)}
  useEffect(()=>{try{const saved=sessionStorage.getItem(draftKey);if(saved)setStrokes(JSON.parse(saved))}catch{}setLoaded(true)},[draftKey]);
  useEffect(()=>{paint();if(loaded)try{sessionStorage.setItem(draftKey,JSON.stringify(strokes))}catch{}},[strokes,loaded]);
  useImperativeHandle(ref,()=>({image:()=>{paint();return canvas.current?.toDataURL('image/png')||''},hasDrawing:()=>strokes.some((s,i)=>!s.clear&&s.color!=='#fff'&&!strokes.slice(i+1).some(t=>t.clear))||!!active.current}));
  function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)*960/r.width,y:(e.clientY-r.top)*600/r.height}}
  function finish(){if(active.current){const s=active.current;active.current=null;pointer.current=null;setStrokes(old=>[...old,s]);setRedo([])}}
  return <div className={`drawing ${compact?'compact':''}`}><div className="canvas-wrap"><canvas ref={canvas} width={960} height={600} aria-label="画板，使用鼠标或手指绘画" onPointerDown={e=>{if(disabled||pointer.current!==null||e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointer.current=e.pointerId;active.current={color:eraser?'#fff':color,width:eraser?width*4:width,points:[point(e)]};paint()}} onPointerMove={e=>{if(active.current&&pointer.current===e.pointerId){active.current.points.push(point(e));paint()}}} onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}/>{!strokes.length&&!active.current&&<div className="canvas-hint"><Pencil size={26}/><span>{compact?'先随手画两笔':'把你的想象画在这里'}</span></div>}</div><div className="drawing-tools"><div className="swatches" aria-label="画笔颜色">{colors.map((c,i)=><button type="button" key={c} aria-label={['墨黑','蓝色','紫色','红色','橙色','黄色','绿色','青绿','浅蓝','粉色'][i]} aria-pressed={!eraser&&color===c} style={{background:c}} disabled={disabled} onClick={()=>{setColor(c);setEraser(false)}}>{!eraser&&color===c&&<Check size={15}/>}</button>)}</div><div className="tool-row"><button type="button" className={`icon-button ${!eraser?'selected':''}`} aria-label="画笔" aria-pressed={!eraser} onClick={()=>setEraser(false)}><Pencil size={18}/></button><button type="button" className={`icon-button ${eraser?'selected':''}`} aria-label="橡皮擦" aria-pressed={eraser} onClick={()=>setEraser(true)}><Eraser size={18}/></button><div className="brush-width"><span style={{width:Math.max(4,width),height:Math.max(4,width)}}/><Slider aria-label="画笔粗细" min={2} max={20} step={1} value={[width]} onValueChange={v=>setWidth(v[0])}/></div><span className="tool-spacer"/><button type="button" className="icon-button" aria-label="撤销" disabled={!strokes.length||disabled} onClick={()=>{setRedo(r=>[...r,strokes[strokes.length-1]]);setStrokes(s=>s.slice(0,-1))}}><Undo2 size={18}/></button><button type="button" className="icon-button" aria-label="重做" disabled={!redo.length||disabled} onClick={()=>{setStrokes(s=>[...s,redo[redo.length-1]]);setRedo(r=>r.slice(0,-1))}}><Redo2 size={18}/></button><button type="button" className="icon-button" aria-label="清空画板（可撤销）" disabled={!strokes.length||disabled} onClick={()=>{setStrokes(s=>[...s,{clear:true,color:'#fff',width:1,points:[]}]);setRedo([])}}><Trash2 size={18}/></button></div></div></div>
});

