"use client";
import {forwardRef,useEffect,useImperativeHandle,useRef,useState} from 'react';
import type {CSSProperties,ReactNode} from 'react';
import {Pencil,Eraser,Undo2,Redo2,Trash2,Check,Maximize2,Minimize2} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {BOARD_WIDTH,BOARD_HEIGHT,MAX_ACTIONS,MAX_POINTS,drawingState,paintDrawing,paintStroke} from '@/lib/drawing';
import type {Stroke,DrawAction,Recording} from '@/lib/drawing';
export type CanvasHandle={revision:()=>number;snapshot:(freeze?:boolean)=>{image:string;recording:Recording};image:()=>string;hasDrawing:()=>boolean;recording:()=>Recording};
const colors=['#202943','#000000','#64748b','#cbd5e1','#ffffff','#7f1d1d','#dc2626','#f87171','#fb923c','#f59e0b','#fde047','#fef08a','#365314','#65a30d','#a3e635','#16a34a','#34d399','#0f766e','#06b6d4','#67e8f9','#1e3a8a','#2548f4','#60a5fa','#a5b4fc','#6d28d9','#a855f7','#e9d5ff','#be185d','#ec4899','#f9a8d4','#78350f','#c68b59'];
const names=['墨黑','黑色','灰色','浅灰','白色','深红','红色','珊瑚红','橘色','金橙','黄色','浅黄','橄榄绿','草绿','青柠','绿色','薄荷绿','墨绿','青色','浅青','藏蓝','蓝色','天蓝','淡蓝','深紫','紫色','淡紫','玫红','粉红','浅粉','棕色','肤色'];
export const DrawingCanvas=forwardRef<CanvasHandle,{draftKey:string;compact?:boolean;disabled?:boolean;source?:ReactNode}>(function DrawingCanvas({draftKey,compact,disabled,source},ref){
 const canvas=useRef<HTMLCanvasElement>(null),active=useRef<Stroke|null>(null),pointer=useRef<number|null>(null),actionsRef=useRef<DrawAction[]>([]);
 const revision=useRef(0),locked=useRef(false);
 const [actions,setActions]=useState<DrawAction[]>([]),[color,setColor]=useState(colors[0]),[width,setWidth]=useState(6),[eraser,setEraser]=useState(false),[expanded,setExpanded]=useState(false),[notice,setNotice]=useState('');
 const [size,setSize]=useState({width:BOARD_WIDTH,height:BOARD_HEIGHT});
 const {strokes,redo}=drawingState(actions);
 function paint(){const ctx=canvas.current?.getContext('2d');if(ctx){paintDrawing(ctx,drawingState(actionsRef.current).strokes);if(active.current)paintStroke(ctx,active.current)}}
 function save(next:DrawAction[]){revision.current++;actionsRef.current=next;setActions(next);try{sessionStorage.setItem(draftKey,JSON.stringify({version:1,width:size.width,height:size.height,actions:next}))}catch{setNotice('浏览器草稿空间不足，请保持页面打开并及时提交。')}}
 useEffect(()=>{let next:DrawAction[]=[];let dimensions=matchMedia('(max-width:760px) and (orientation:portrait)').matches?{width:600,height:800}:{width:BOARD_WIDTH,height:BOARD_HEIGHT};try{const raw=sessionStorage.getItem(draftKey);if(raw){const data=JSON.parse(raw);dimensions={width:data.width||BOARD_WIDTH,height:data.height||BOARD_HEIGHT};next=Array.isArray(data)?data.map((s:Stroke)=>s.clear?{type:'clear'}:{type:'stroke',stroke:{...s,color:s.color==='#fff'?'#ffffff':s.color}}):data.actions||[];if(!next.length)dimensions=matchMedia('(max-width:760px) and (orientation:portrait)').matches?{width:600,height:800}:dimensions}}catch{}locked.current=false;revision.current++;setSize(dimensions);actionsRef.current=next;setActions(next);active.current=null;pointer.current=null;},[draftKey]);
 useEffect(()=>{paint()},[actions,expanded,size]);
 useEffect(()=>{if(!expanded)return;const before=document.body.style.overflow;document.body.style.overflow='hidden';const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setExpanded(false)};window.addEventListener('keydown',key);return()=>{document.body.style.overflow=before;window.removeEventListener('keydown',key)}},[expanded]);
 function allActions(){return active.current?[...actionsRef.current,{type:'stroke' as const,stroke:active.current}]:actionsRef.current}
 useImperativeHandle(ref,()=>({revision:()=>revision.current,snapshot:(freeze=false)=>{if(freeze){locked.current=true;finish()}paint();return {image:canvas.current?.toDataURL('image/png')||'',recording:structuredClone({version:1,width:size.width,height:size.height,actions:allActions()})}},image:()=>{paint();return canvas.current?.toDataURL('image/png')||''},recording:()=>({version:1,width:size.width,height:size.height,actions:allActions()}),hasDrawing:()=>{const s=drawingState(allActions()).strokes;return s.some((a,i)=>!a.clear&&a.color!=='#ffffff'&&!s.slice(i+1).some(b=>b.clear))}}));
 function point(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();return{x:Math.round(Math.max(0,Math.min(size.width,(e.clientX-r.left)*size.width/r.width))*10)/10,y:Math.round(Math.max(0,Math.min(size.height,(e.clientY-r.top)*size.height/r.height))*10)/10}}
 function finish(){if(active.current){const stroke=active.current;active.current=null;pointer.current=null;save([...actionsRef.current,{type:'stroke',stroke}])}}
 function edit(action:DrawAction){if(disabled||locked.current)return;if(actionsRef.current.length>=MAX_ACTIONS){setNotice('这幅画的操作次数已满，请提交当前作品。');return}save([...actionsRef.current,action])}
 const usedPoints=useRef(0);
 return <div style={{'--board-ratio':size.width/size.height} as CSSProperties} className={`drawing ${compact?'compact':''} ${expanded?'expanded':''} ${source?'with-source':''}`}>
  {source}
  <div className="canvas-heading"><span>{compact?'随手画画':'你的画布'}{expanded&&' · 按 Esc 收起'}</span><button type="button" className="text-button" onClick={()=>setExpanded(v=>!v)}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}<span>{expanded?'收起画布':'放大画布'}</span></button></div>
  <div className="canvas-wrap"><canvas ref={canvas} width={size.width} height={size.height} aria-label="画板，使用鼠标或手指绘画"
   onPointerDown={e=>{if(disabled||locked.current||pointer.current!==null||e.button!==0)return;usedPoints.current=actionsRef.current.reduce((n,a)=>n+(a.type==='stroke'?a.stroke.points.length:0),0);if(usedPoints.current>=MAX_POINTS||actionsRef.current.length>=MAX_ACTIONS){setNotice('这幅画的笔画已满，请提交当前作品。');return}e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointer.current=e.pointerId;revision.current++;active.current={color:eraser?'#ffffff':color,width:eraser?width*4:width,points:[point(e)]};paint()}}
   onPointerMove={e=>{const s=active.current;if(disabled||locked.current||!s||pointer.current!==e.pointerId)return;const p=point(e),last=s.points[s.points.length-1];if(Math.hypot(p.x-last.x,p.y-last.y)<1.5)return;if(usedPoints.current+s.points.length>=MAX_POINTS){finish();setNotice('这幅画的笔画已满，请提交当前作品。');return}s.points.push(p);revision.current++;paint()}}
   onPointerUp={finish} onPointerCancel={finish} onLostPointerCapture={finish}/>
   {!strokes.length&&!active.current&&<div className="canvas-hint"><Pencil size={30}/><span>{compact?'先随手画两笔':'把你的想象画在这里'}</span></div>}
  </div>
  <div className="drawing-tools"><div className="swatches" aria-label="画笔颜色">{colors.map((c,i)=><button type="button" key={c} aria-label={names[i]} title={names[i]} aria-pressed={!eraser&&color===c} style={{background:c,color:['#ffffff','#fde047','#fef08a','#cbd5e1'].includes(c)?'#202943':'white'}} disabled={disabled} onClick={()=>{setColor(c);setEraser(false)}}>{!eraser&&color===c&&<Check size={15}/>}</button>)}<label className="custom-color" title="自定义颜色"><input type="color" aria-label="自定义画笔颜色" value={color} disabled={disabled} onChange={e=>{setColor(e.target.value);setEraser(false)}}/><span>自选</span></label></div>
   <div className="tool-row"><button type="button" className={`icon-button ${!eraser?'selected':''}`} aria-label="画笔" aria-pressed={!eraser} disabled={disabled} onClick={()=>setEraser(false)}><Pencil size={18}/></button><button type="button" className={`icon-button ${eraser?'selected':''}`} aria-label="橡皮擦" aria-pressed={eraser} disabled={disabled} onClick={()=>setEraser(true)}><Eraser size={18}/></button><div className="brush-width"><span style={{width:Math.max(4,width),height:Math.max(4,width)}}/><Slider aria-label="画笔粗细" min={2} max={20} step={1} value={[width]} disabled={disabled} onValueChange={v=>setWidth(v[0])}/></div><span className="tool-spacer"/><button type="button" className="icon-button" aria-label="撤销" disabled={!strokes.length||disabled} onClick={()=>edit({type:'undo'})}><Undo2 size={18}/></button><button type="button" className="icon-button" aria-label="重做" disabled={!redo.length||disabled} onClick={()=>edit({type:'redo'})}><Redo2 size={18}/></button><button type="button" className="icon-button" aria-label="清空画板（可撤销）" disabled={!strokes.length||disabled} onClick={()=>edit({type:'clear'})}><Trash2 size={18}/></button></div>
  </div>{notice&&<p className="muted" role="status">{notice}</p>}
 </div>
});
